### ISSUE TITLE
(13)Elaborar o design (view) para as telas de login, cadastro e gerenciamento de perfil

### ISSUE THREAD

**Issue by jorgecrodrigues** [kFurlan/SmartHome#11]
Se esta atividade levar muito tempo, dividi-la em partes

**Comment by lucasafranio77** [comment]
Gente fiz o prototipo da tela de login e do cadastro:

[Link do protótipo](https://xd.adobe.com/view/27dc2151-7293-460e-533f-11c822ea0de0-51ed/)
[Link do Design Specs](https://xd.adobe.com/spec/844800d3-124d-449a-42b4-130a1e8b1e86-f279/)

Aqui segue a documentação do [material.io](material.io)

e aqui a do material ligado ao flutter: https://material.io/develop/flutter/

https://docs.flutter.io/flutter/material/material-library.html

@jorgecrodrigues @fuzzyqu @kFurlan 

Comente ai o que vai ter na parte de gerenciamento de perfil, o que vai ta editável e o que não.
Pra eu fazer essa parte ai. Essa parte do gerenciamento vai ser acessado pelo menu ne? esse seria o fluxo dela?

**Comment by kFurlan** [comment]
oloco, o cara é bom!

**Comment by kFurlan** [comment]
@lucasafranio77 não sei se precisa mudar no protótipo ja que eu vou fazer a tela de cadastro, mas eu acho melhor trocar o botão login na segunda tela para cadastrar.

**Comment by usr-igu** [comment]
Ficou top. 

a única informação não editável vai ser o e-mail, os dados estão na issue #12

**Comment by lucasafranio77** [comment]
Fiz a parte de editar o perfil lá, dá uma olhada e me fala o que acha. O prototipo e o design specs estão no mesmo link.

O primeiro artboard dai, seria a tela principal com o menu embaixo, pois assim facilita a visualização das informações, então coloquei na outra artboard o perfil, que vai ter aqueles outros espaços relacionados a configurações, e lá tbm ficou a parte de editar o perfil.

Em relação aos outros botões do menu e outra telas, vou mexer ainda.

![image](https://user-images.githubusercontent.com/6682414/49690481-7e312a80-fb10-11e8-8429-fcd40f2e7504.png)

Dá uma olhada ai e me falam o que acha. Sobre a senha, acho que se clicasse ali teria que abrir outra tela pra editar, o que acha @fuzzyqu ?

PS: @kFurlan valeu por avisar sobre o botão, atualizei la

**Comment by lucasafranio77** [comment]
<iframe width="360" height="740" src="https://xd.adobe.com/embed/27dc2151-7293-460e-533f-11c822ea0de0-51ed/" frameborder="0" allowfullscreen></iframe>
